version: '3.8'

services:
  sushe-stargate:
    build: .
    container_name: sushe-stargate
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - BASE_URL=${BASE_URL}
      - NODE_ENV=production
      - DATA_DIR=/app/data
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS:-30}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  data:
    driver: local